spring:
  application:
    name: cqrs-commender
  datasource:
    url: jdbc:mariadb://localhost:3306/testdb
    username: test
    password: test
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
